include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - avoid_print
    - avoid_empty_else
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_single_quotes
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - unawaited_futures
    - use_key_in_widget_constructors
